// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR2370mKL5nHI0hLa_PKSzgG8hz38U0iM',
    appId: '1:735119237084:web:2d57c1121c4d61d6ccf919',
    messagingSenderId: '735119237084',
    projectId: 'chat-app-f889e',
    authDomain: 'chat-app-f889e.firebaseapp.com',
    storageBucket: 'chat-app-f889e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0oEb5l4sfJ-ofJR6S21Hcul8-BSCu7qI',
    appId: '1:735119237084:android:e40724411482e110ccf919',
    messagingSenderId: '735119237084',
    projectId: 'chat-app-f889e',
    storageBucket: 'chat-app-f889e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZNnk0ILeISJ51DIAk0b1PbrDdtuFfg64',
    appId: '1:735119237084:ios:37709d968064f423ccf919',
    messagingSenderId: '735119237084',
    projectId: 'chat-app-f889e',
    storageBucket: 'chat-app-f889e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZNnk0ILeISJ51DIAk0b1PbrDdtuFfg64',
    appId: '1:735119237084:ios:37709d968064f423ccf919',
    messagingSenderId: '735119237084',
    projectId: 'chat-app-f889e',
    storageBucket: 'chat-app-f889e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR2370mKL5nHI0hLa_PKSzgG8hz38U0iM',
    appId: '1:735119237084:web:73b23171359a9f3fccf919',
    messagingSenderId: '735119237084',
    projectId: 'chat-app-f889e',
    authDomain: 'chat-app-f889e.firebaseapp.com',
    storageBucket: 'chat-app-f889e.firebasestorage.app',
  );
}
